[package]
name = "betting"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }

[[target.starknet-contract]]
sierra = true

[cairo]
sierra-replace-ids = true
